version: '3.8'

services:
  vue-app:
    build:
      context: .
    container_name: vue-app
    ports:
      - "80:80"
    networks:
      - repository-of-research-works_sail

networks:
  repository-of-research-works_sail:
    external: true